<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-02-14T15:25:44+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'tastytours',
    'version_installed' => '5.7.5.3',
    'misc' => array(
        'access_entity_updated' => 1451845376,
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.6',
    ),
);
