<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-03-14T03:48:06+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      maintenance.version_job_page_num
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'tastytours',
    'version_installed' => '5.7.5.6',
    'misc' => array(
        'access_entity_updated' => 1451845376,
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.6',
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
    'maintenance' => array(
        'version_job_page_num' => '160',
    ),
);
